In [1]:
import tensorflow as ts
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
inde=data.iloc[:,3:-1]#because the customer id is not a dependent feature
depe=data.iloc[:,-1]
inde

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [4]:
#convert words into values
geo=pd.get_dummies(data['Geography'],dtype=int,drop_first=True)
gend=pd.get_dummies(data['Gender'],dtype=int,drop_first=True)

In [5]:
inde=inde.drop(['Geography','Gender'],axis=1)
inde

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,42,2,0.00,1,1,1,101348.88
1,608,41,1,83807.86,1,0,1,112542.58
2,502,42,8,159660.80,3,1,0,113931.57
3,699,39,1,0.00,2,0,0,93826.63
4,850,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64
9996,516,35,10,57369.61,1,1,1,101699.77
9997,709,36,7,0.00,1,0,1,42085.58
9998,772,42,3,75075.31,2,1,0,92888.52
9999,792,28,4,130142.79,1,1,0,38190.78

In [6]:

inde=pd.concat([inde,geo,gend],axis=1)
inde

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inde,depe,test_size=0.33, random_state=0)
x_test

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
9394,597,35,8,131101.04,1,1,1,192852.67,1,0,0
898,523,40,2,102967.41,1,1,0,128702.10,0,0,0
2398,706,42,8,95386.82,1,1,1,75732.25,0,1,0
5906,788,32,4,112079.58,1,0,0,89368.59,0,0,1
2343,706,38,5,163034.82,2,1,1,135662.17,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...
4142,637,63,5,0.00,1,1,0,28092.77,0,0,0
2067,744,31,9,120718.28,1,1,1,58961.49,0,0,1
768,684,41,2,119782.72,2,0,0,120284.67,0,1,1
5927,577,43,3,127940.47,1,0,0,125140.72,1,0,0
2644,736,27,5,51522.75,1,0,1,192131.77,0,0,1

In [8]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
x_train=scale.fit_transform(x_train)
x_test=scale.transform(x_test)

In [9]:
# creating ANN
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU,ReLU
from tensorflow.keras.layers import Dropout

In [10]:
model=Sequential()

model.add(Dense(units=11,activation='relu'))
model.add(Dense(units=10,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(units=7,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(units=1,activation='sigmoid'))
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])
early_sto=ts.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    min_delta=0.0001,
    patience=1,
    verbose=0,
    mode='auto',
    baseline=None,
    restore_best_weights=False,
    start_from_epoch=0
)

In [11]:
model_total=model.fit(x_train,y_train,batch_size=20, epochs=100,callbacks=[early_sto])

Epoch 1/100

2023-10-06 12:28:17.513123: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-10-06 12:28:18.427410: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_10.

331/335 [============================>.] - ETA: 0s - loss: 0.6065 - accuracy: 0.6989WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 5s 6ms/step - loss: 0.6046 - accuracy: 0.6999
Epoch 2/100
328/335 [============================>.] - ETA: 0s - loss: 0.4990 - accuracy: 0.7893WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4983 - accuracy: 0.7893
Epoch 3/100
331/335 [============================>.] - ETA: 0s - loss: 0.4794 - accuracy: 0.7992WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4791 - accuracy: 0.7993
Epoch 4/100
335/335 [==============================] - ETA: 0s - loss: 0.4748 - accuracy: 0.7951WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4748 - accuracy: 0.7951
Epoch 5/100
334/335 [============================>.] - ETA: 0s - loss: 0.4716 - accuracy: 0.8021WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4715 - accuracy: 0.8024
Epoch 6/100
335/335 [==============================] - ETA: 0s - loss: 0.4873 - accuracy: 0.7979WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4873 - accuracy: 0.7979
Epoch 7/100
333/335 [============================>.] - ETA: 0s - loss: 0.4878 - accuracy: 0.7992WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4878 - accuracy: 0.7993
Epoch 8/100
327/335 [============================>.] - ETA: 0s - loss: 0.4661 - accuracy: 0.7982WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4645 - accuracy: 0.7990
Epoch 9/100
335/335 [==============================] - ETA: 0s - loss: 0.4646 - accuracy: 0.7996WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4646 - accuracy: 0.7996
Epoch 10/100
328/335 [============================>.] - ETA: 0s - loss: 0.4603 - accuracy: 0.7998WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4607 - accuracy: 0.7991
Epoch 11/100
335/335 [==============================] - ETA: 0s - loss: 0.4549 - accuracy: 0.7988WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4549 - accuracy: 0.7988
Epoch 12/100
327/335 [============================>.] - ETA: 0s - loss: 0.4541 - accuracy: 0.8031WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4553 - accuracy: 0.8016
Epoch 13/100
335/335 [==============================] - ETA: 0s - loss: 0.4530 - accuracy: 0.8001WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4530 - accuracy: 0.8001
Epoch 14/100
334/335 [============================>.] - ETA: 0s - loss: 0.4541 - accuracy: 0.7984WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4542 - accuracy: 0.7982
Epoch 15/100
334/335 [============================>.] - ETA: 0s - loss: 0.4562 - accuracy: 0.7975WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4565 - accuracy: 0.7972
Epoch 16/100
334/335 [============================>.] - ETA: 0s - loss: 0.4498 - accuracy: 0.7997WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4499 - accuracy: 0.7997
Epoch 17/100
335/335 [==============================] - ETA: 0s - loss: 0.4563 - accuracy: 0.8004WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4563 - accuracy: 0.8004
Epoch 18/100
333/335 [============================>.] - ETA: 0s - loss: 0.4521 - accuracy: 0.7983WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4524 - accuracy: 0.7982
Epoch 19/100
333/335 [============================>.] - ETA: 0s - loss: 0.4579 - accuracy: 0.8029WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4574 - accuracy: 0.8033
Epoch 20/100
333/335 [============================>.] - ETA: 0s - loss: 0.4552 - accuracy: 0.8009WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4551 - accuracy: 0.8012
Epoch 21/100
334/335 [============================>.] - ETA: 0s - loss: 0.4565 - accuracy: 0.8010WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4559 - accuracy: 0.8013
Epoch 22/100
333/335 [============================>.] - ETA: 0s - loss: 0.4614 - accuracy: 0.7998WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4620 - accuracy: 0.7994
Epoch 23/100
335/335 [==============================] - ETA: 0s - loss: 0.4628 - accuracy: 0.8016WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4628 - accuracy: 0.8016
Epoch 24/100
334/335 [============================>.] - ETA: 0s - loss: 0.4562 - accuracy: 0.7993WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4560 - accuracy: 0.7994
Epoch 25/100
331/335 [============================>.] - ETA: 0s - loss: 0.4585 - accuracy: 0.7992WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4598 - accuracy: 0.7981
Epoch 26/100
327/335 [============================>.] - ETA: 0s - loss: 0.4599 - accuracy: 0.8005WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4598 - accuracy: 0.8009
Epoch 27/100

326/335 [============================>.] - ETA: 0s - loss: 0.4622 - accuracy: 0.8028WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4620 - accuracy: 0.8034
Epoch 28/100
334/335 [============================>.] - ETA: 0s - loss: 0.4667 - accuracy: 0.7966WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4669 - accuracy: 0.7963
Epoch 29/100
327/335 [============================>.] - ETA: 0s - loss: 0.4541 - accuracy: 0.8044WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4549 - accuracy: 0.8027
Epoch 30/100
334/335 [============================>.] - ETA: 0s - loss: 0.4608 - accuracy: 0.7978WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4611 - accuracy: 0.7976
Epoch 31/100
332/335 [============================>.] - ETA: 0s - loss: 0.4660 - accuracy: 0.8008WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4659 - accuracy: 0.8010
Epoch 32/100
331/335 [============================>.] - ETA: 0s - loss: 0.4667 - accuracy: 0.8047WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 7ms/step - loss: 0.4661 - accuracy: 0.8052
Epoch 33/100
332/335 [============================>.] - ETA: 0s - loss: 0.4779 - accuracy: 0.8009WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4772 - accuracy: 0.8016
Epoch 34/100
330/335 [============================>.] - ETA: 0s - loss: 0.4670 - accuracy: 0.7968WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4648 - accuracy: 0.7978
Epoch 35/100
327/335 [============================>.] - ETA: 0s - loss: 0.4614 - accuracy: 0.8006WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4591 - accuracy: 0.8016
Epoch 36/100
332/335 [============================>.] - ETA: 0s - loss: 0.4660 - accuracy: 0.8045WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4664 - accuracy: 0.8045
Epoch 37/100
333/335 [============================>.] - ETA: 0s - loss: 0.4776 - accuracy: 0.7979WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4776 - accuracy: 0.7978
Epoch 38/100
327/335 [============================>.] - ETA: 0s - loss: 0.4730 - accuracy: 0.7979WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4725 - accuracy: 0.7985
Epoch 39/100
332/335 [============================>.] - ETA: 0s - loss: 0.4824 - accuracy: 0.7970WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4814 - accuracy: 0.7973
Epoch 40/100
332/335 [============================>.] - ETA: 0s - loss: 0.4569 - accuracy: 0.8056WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 7ms/step - loss: 0.4583 - accuracy: 0.8051
Epoch 41/100
334/335 [============================>.] - ETA: 0s - loss: 0.4664 - accuracy: 0.8042WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 7ms/step - loss: 0.4662 - accuracy: 0.8043
Epoch 42/100
331/335 [============================>.] - ETA: 0s - loss: 0.4768 - accuracy: 0.8005WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4765 - accuracy: 0.8004
Epoch 43/100
335/335 [==============================] - ETA: 0s - loss: 0.4782 - accuracy: 0.7999WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4782 - accuracy: 0.7999
Epoch 44/100
328/335 [============================>.] - ETA: 0s - loss: 0.4678 - accuracy: 0.8009WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4687 - accuracy: 0.8001
Epoch 45/100
335/335 [==============================] - ETA: 0s - loss: 0.4829 - accuracy: 0.7973WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4829 - accuracy: 0.7973
Epoch 46/100
334/335 [============================>.] - ETA: 0s - loss: 0.4676 - accuracy: 0.8021WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4677 - accuracy: 0.8018
Epoch 47/100
332/335 [============================>.] - ETA: 0s - loss: 0.4701 - accuracy: 0.8017WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4692 - accuracy: 0.8019
Epoch 48/100
332/335 [============================>.] - ETA: 0s - loss: 0.4704 - accuracy: 0.8017WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4714 - accuracy: 0.8010
Epoch 49/100
326/335 [============================>.] - ETA: 0s - loss: 0.4728 - accuracy: 0.8034WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4732 - accuracy: 0.8030
Epoch 50/100
327/335 [============================>.] - ETA: 0s - loss: 0.4781 - accuracy: 0.7946WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4782 - accuracy: 0.7949
Epoch 51/100
330/335 [============================>.] - ETA: 0s - loss: 0.4701 - accuracy: 0.8023WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4708 - accuracy: 0.8016
Epoch 52/100
335/335 [==============================] - ETA: 0s - loss: 0.4763 - accuracy: 0.8021WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4763 - accuracy: 0.8021
Epoch 53/100

332/335 [============================>.] - ETA: 0s - loss: 0.4764 - accuracy: 0.7995WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4783 - accuracy: 0.7990
Epoch 54/100
327/335 [============================>.] - ETA: 0s - loss: 0.4730 - accuracy: 0.7979WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4707 - accuracy: 0.7987
Epoch 55/100
332/335 [============================>.] - ETA: 0s - loss: 0.4784 - accuracy: 0.7982WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4776 - accuracy: 0.7985
Epoch 56/100
335/335 [==============================] - ETA: 0s - loss: 0.4663 - accuracy: 0.8001WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4663 - accuracy: 0.8001
Epoch 57/100
335/335 [==============================] - ETA: 0s - loss: 0.4714 - accuracy: 0.8001WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4714 - accuracy: 0.8001
Epoch 58/100
331/335 [============================>.] - ETA: 0s - loss: 0.4818 - accuracy: 0.7989WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4817 - accuracy: 0.7993
Epoch 59/100
335/335 [==============================] - ETA: 0s - loss: 0.4807 - accuracy: 0.8009WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4807 - accuracy: 0.8009
Epoch 60/100
331/335 [============================>.] - ETA: 0s - loss: 0.4669 - accuracy: 0.8009WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4671 - accuracy: 0.8010
Epoch 61/100
330/335 [============================>.] - ETA: 0s - loss: 0.4789 - accuracy: 0.7997WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4793 - accuracy: 0.7988
Epoch 62/100
335/335 [==============================] - ETA: 0s - loss: 0.4674 - accuracy: 0.7982WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4674 - accuracy: 0.7982
Epoch 63/100
328/335 [============================>.] - ETA: 0s - loss: 0.4696 - accuracy: 0.7980WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4676 - accuracy: 0.7990
Epoch 64/100
332/335 [============================>.] - ETA: 0s - loss: 0.4838 - accuracy: 0.7944WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4826 - accuracy: 0.7949
Epoch 65/100
335/335 [==============================] - ETA: 0s - loss: 0.4766 - accuracy: 0.7990WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4766 - accuracy: 0.7990
Epoch 66/100
328/335 [============================>.] - ETA: 0s - loss: 0.4657 - accuracy: 0.8015WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4639 - accuracy: 0.8019
Epoch 67/100
330/335 [============================>.] - ETA: 0s - loss: 0.4860 - accuracy: 0.7965WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 5ms/step - loss: 0.4849 - accuracy: 0.7972
Epoch 68/100
329/335 [============================>.] - ETA: 0s - loss: 0.4733 - accuracy: 0.8015WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 5ms/step - loss: 0.4743 - accuracy: 0.8015
Epoch 69/100
326/335 [============================>.] - ETA: 0s - loss: 0.4781 - accuracy: 0.7952WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4786 - accuracy: 0.7943
Epoch 70/100
329/335 [============================>.] - ETA: 0s - loss: 0.4766 - accuracy: 0.8003WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4790 - accuracy: 0.7994
Epoch 71/100
334/335 [============================>.] - ETA: 0s - loss: 0.4851 - accuracy: 0.7984WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4848 - accuracy: 0.7982
Epoch 72/100
333/335 [============================>.] - ETA: 0s - loss: 0.4766 - accuracy: 0.7968WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4763 - accuracy: 0.7972
Epoch 73/100
332/335 [============================>.] - ETA: 0s - loss: 0.4689 - accuracy: 0.8003WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4690 - accuracy: 0.8003
Epoch 74/100
327/335 [============================>.] - ETA: 0s - loss: 0.4728 - accuracy: 0.8003WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4719 - accuracy: 0.8004
Epoch 75/100
327/335 [============================>.] - ETA: 0s - loss: 0.4768 - accuracy: 0.8041WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4777 - accuracy: 0.8042
Epoch 76/100
335/335 [==============================] - ETA: 0s - loss: 0.4781 - accuracy: 0.7961WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4781 - accuracy: 0.7961
Epoch 77/100
329/335 [============================>.] - ETA: 0s - loss: 0.4667 - accuracy: 0.8027WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4661 - accuracy: 0.8030
Epoch 78/100
326/335 [============================>.] - ETA: 0s - loss: 0.4687 - accuracy: 0.8002WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4700 - accuracy: 0.7993
Epoch 79/100

335/335 [==============================] - ETA: 0s - loss: 0.4759 - accuracy: 0.8019WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4759 - accuracy: 0.8019
Epoch 80/100
326/335 [============================>.] - ETA: 0s - loss: 0.4781 - accuracy: 0.7997WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4801 - accuracy: 0.7990
Epoch 81/100
327/335 [============================>.] - ETA: 0s - loss: 0.4869 - accuracy: 0.7974WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4852 - accuracy: 0.7976
Epoch 82/100
329/335 [============================>.] - ETA: 0s - loss: 0.4766 - accuracy: 0.7988WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4768 - accuracy: 0.7991
Epoch 83/100
327/335 [============================>.] - ETA: 0s - loss: 0.4661 - accuracy: 0.8034WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4666 - accuracy: 0.8030
Epoch 84/100
331/335 [============================>.] - ETA: 0s - loss: 0.4719 - accuracy: 0.8018WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4733 - accuracy: 0.8018
Epoch 85/100
327/335 [============================>.] - ETA: 0s - loss: 0.4787 - accuracy: 0.8006WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4783 - accuracy: 0.8006
Epoch 86/100
335/335 [==============================] - ETA: 0s - loss: 0.4642 - accuracy: 0.8015WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4642 - accuracy: 0.8015
Epoch 87/100
333/335 [============================>.] - ETA: 0s - loss: 0.4677 - accuracy: 0.8050WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4673 - accuracy: 0.8049
Epoch 88/100
330/335 [============================>.] - ETA: 0s - loss: 0.4689 - accuracy: 0.8045WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4710 - accuracy: 0.8039
Epoch 89/100
334/335 [============================>.] - ETA: 0s - loss: 0.4684 - accuracy: 0.8018WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4679 - accuracy: 0.8021
Epoch 90/100
329/335 [============================>.] - ETA: 0s - loss: 0.4682 - accuracy: 0.8002WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4685 - accuracy: 0.8003
Epoch 91/100
332/335 [============================>.] - ETA: 0s - loss: 0.4682 - accuracy: 0.7992WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4680 - accuracy: 0.7994
Epoch 92/100
327/335 [============================>.] - ETA: 0s - loss: 0.4639 - accuracy: 0.8014WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4639 - accuracy: 0.8010
Epoch 93/100
335/335 [==============================] - ETA: 0s - loss: 0.4723 - accuracy: 0.8003WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4723 - accuracy: 0.8003
Epoch 94/100
331/335 [============================>.] - ETA: 0s - loss: 0.4769 - accuracy: 0.7973WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4755 - accuracy: 0.7985
Epoch 95/100
328/335 [============================>.] - ETA: 0s - loss: 0.4598 - accuracy: 0.8059WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4613 - accuracy: 0.8049
Epoch 96/100
334/335 [============================>.] - ETA: 0s - loss: 0.4664 - accuracy: 0.8007WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4668 - accuracy: 0.8007
Epoch 97/100
331/335 [============================>.] - ETA: 0s - loss: 0.4665 - accuracy: 0.7979WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4686 - accuracy: 0.7982
Epoch 98/100
334/335 [============================>.] - ETA: 0s - loss: 0.4584 - accuracy: 0.7999WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4586 - accuracy: 0.7997
Epoch 99/100
333/335 [============================>.] - ETA: 0s - loss: 0.4621 - accuracy: 0.7992WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 6ms/step - loss: 0.4631 - accuracy: 0.7984
Epoch 100/100
332/335 [============================>.] - ETA: 0s - loss: 0.4599 - accuracy: 0.7973WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
335/335 [==============================] - 2s 7ms/step - loss: 0.4601 - accuracy: 0.7970

In [12]:
model_total.history.keys()

dict_keys(['loss', 'accuracy'])

In [13]:
new_predict=model.predict(x_test)
new_predict=(new_predict>=0.5)
new_predict = new_predict.astype(int)
new_predict

104/104 [==============================] - 0s 3ms/step

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [14]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
matr=confusion_matrix(y_test,new_predict)
matr

array([[2503,  114],
       [ 569,  114]])

In [15]:
accura=accuracy_score(new_predict,y_test)
accura

0.7930303030303031

In [16]:
#for the weights we should do
model.get_weights()

[array([[-8.49673450e-02, -2.66752154e-01, -8.33700318e-03,
         -2.74579227e-01,  3.54131073e-01, -8.01444650e-02,
          9.19865593e-02, -8.66624415e-02, -2.49184728e-01,
         -3.29183340e-01, -2.37286001e-01],
        [ 1.07176042e+00, -2.44713330e+00,  1.09671938e+00,
          9.13488567e-01, -2.68229651e+00,  7.87513673e-01,
         -1.12992013e+00,  1.15390980e+00,  1.10205138e+00,
          9.31856930e-01,  2.34800196e+00],
        [-1.48063466e-01,  5.33029251e-02, -7.27557316e-02,
          1.55828655e-01,  4.83528823e-01, -1.06323414e-01,
         -2.87205160e-01, -1.10819325e-01,  3.19116056e-01,
          6.51545748e-02,  1.39899954e-01],
        [ 2.32880425e+00, -1.76107192e+00,  2.79368258e+00,
         -3.54764009e+00, -1.87177193e+00,  2.64459252e+00,
         -1.61769009e+00,  2.93168998e+00, -1.78726745e+00,
         -3.27262044e+00, -4.36022663e+00],
        [ 6.89077711e+00,  1.59014261e+00,  7.49839687e+00,
         -6.85523891e+00, -1.33006334e-01,  6.86462307e+00,
         -8.21075022e-01,  7.55788183e+00, -5.90488863e+00,
         -6.85657358e+00, -7.33726406e+00],
        [-7.89937004e-02, -1.01734400e-01, -6.72637150e-02,
          1.96709275e-01,  3.61387074e-01, -1.19189426e-01,
         -1.87854737e-01, -1.34478837e-01, -7.70928115e-02,
          1.50748610e-01, -4.01331484e-03],
        [-3.64829361e-01,  1.68980919e-02, -1.35709465e-01,
         -7.75936544e-01,  7.28069484e-01, -1.64863646e-01,
          2.91953951e-01, -2.27022395e-01,  1.26816317e-01,
         -1.21245813e+00, -9.86073196e-01],
        [-5.72032668e-03,  7.92203322e-02, -2.39703506e-01,
          3.38643432e-01, -8.37029070e-02, -1.14743754e-01,
         -2.65426129e-01, -1.40199229e-01,  1.04034215e-01,
          3.43462884e-01,  9.36744958e-02],
        [-1.41229498e+00, -2.22760096e-01, -1.55637789e+00,
          2.29040432e+00, -1.74572635e+00, -1.51531112e+00,
          2.03304863e+00, -1.61766255e+00,  3.42792839e-01,
          2.38377929e+00,  3.03996086e+00],
        [ 1.78684980e-01, -9.83813226e-01,  2.86824048e-01,
         -2.29328007e-01, -1.53698683e-01,  1.82767913e-01,
          4.77272481e-01,  2.24118561e-01, -1.52344078e-01,
         -2.75474608e-01, -3.31815809e-01],
        [-4.15511318e-02,  1.04880297e+00, -1.94500193e-01,
         -2.84910440e-01,  1.15556133e+00, -1.16716325e-03,
          4.67286468e-01, -6.32629469e-02, -2.27067202e-01,
         -2.58590370e-01, -3.78763735e-01]], dtype=float32),
 array([-3.0842538,  1.3689177, -3.0883164,  2.0505538,  1.3365673,
        -2.989118 ,  3.76683  , -3.1109333,  2.724578 ,  2.1179788,
         2.0748985], dtype=float32),
 array([[-4.045081  ,  4.4372396 , -2.407432  , -1.543369  , -0.9644356 ,
         -0.25941724, -0.48238516, -2.3624036 ,  4.4030204 ,  6.76978   ],
        [-3.227272  ,  2.160605  , -1.3478931 , -1.7602875 ,  2.0273442 ,
          1.6659942 ,  0.19186215, -1.5252495 ,  1.4556575 ,  2.4320834 ],
        [-4.2595825 ,  3.7890525 , -2.8615181 , -2.0379467 , -0.60820335,
         -1.1659776 , -0.48436216, -2.8568375 ,  5.0799937 ,  6.5290923 ],
        [ 5.2002225 , -2.6668603 ,  3.8308737 ,  4.5678062 , -1.1158589 ,
         -0.8959565 ,  1.5444558 ,  3.834328  , -3.4274616 , -4.7816796 ],
        [ 0.7579533 , -0.86027354,  0.3849214 , -0.9305223 ,  2.071932  ,
          1.912484  ,  0.04973242,  0.3387192 , -1.8724865 , -1.5413564 ],
        [-3.8516514 ,  4.6386604 , -2.682889  , -2.2039495 , -0.7400223 ,
         -0.92727166, -0.6527007 , -2.6244466 ,  4.5539994 ,  6.155724  ],
        [ 3.823602  , -4.960088  ,  2.0320108 ,  1.3749417 ,  0.30337656,
          0.47910374,  0.31099084,  2.0368347 , -3.382702  , -6.91844   ],
        [-4.5375414 ,  4.0300074 , -3.254685  , -2.2384505 , -0.7233364 ,
         -1.0715882 , -0.9794534 , -3.303013  ,  4.8663874 ,  6.459848  ],
        [ 3.0895712 , -2.5852437 ,  0.68157005,  1.4627194 , -0.3401934 ,
         -0.6403015 , -1.2551818 ,  0.33022222, -2.3824322 , -4.112571  ],
        [ 4.609811  , -3.185959  ,  4.121517  ,  4.181208  , -0.48972517,
         -0.81555355,  1.4787399 ,  4.348036  , -4.122848  , -4.3651586 ],
        [ 6.3536196 , -3.6670728 ,  4.2476134 ,  4.7867947 , -0.9017511 ,
         -1.1613253 ,  1.3197759 ,  4.8240013 , -3.2191448 , -5.1978927 ]],
       dtype=float32),
 array([ 3.0221968 , -2.8732722 , -0.03640781,  0.21379235,  0.39249635,
         0.5226526 , -1.3809345 ,  0.10607588,  0.5011961 , -3.1748006 ],
       dtype=float32),
 array([[-1.98894650e-01, -5.01294062e-02, -3.42040434e-02,
          5.54928407e-02, -2.01549366e-01, -1.37327194e-01,
          3.80796939e-02],
        [ 8.26475322e-02,  1.13626570e-01, -5.27919270e-03,
         -6.41520321e-03, -7.37475604e-02,  2.20589250e-01,
         -3.98807116e-02],
        [ 3.73051375e-01,  9.56128091e-02, -2.40230327e-03,
         -1.87343191e-02, -4.20975275e-02,  8.15546095e-01,
         -6.98657110e-02],
        [ 6.92399740e-02,  7.17342049e-02,  3.44791971e-02,
         -1.92959085e-02, -1.22938432e-01, -2.93723065e-02,
         -1.05632849e-01],
        [-8.42367709e-02,  2.06442252e-02,  7.59635448e-01,
          1.14735818e+00,  2.51652646e+00, -3.57885271e-01,
          2.32972980e+00],
        [ 7.80326873e-02,  1.76500589e-01,  2.52697134e+00,
          1.46556473e+00,  3.34849238e+00, -1.46546245e-01,
          1.59152555e+00],
        [ 8.80605578e-01,  1.30156234e-01,  3.61076221e-02,
         -3.09472144e-01,  2.58105218e-01,  1.52996212e-01,
          3.09064239e-01],
        [ 2.92164356e-01,  1.45498306e-01, -8.56037717e-03,
         -1.92424916e-02, -1.76229045e-01, -3.70782852e-01,
         -3.05271875e-02],
        [-1.43983334e-01, -1.02897935e-01, -2.02337559e-03,
          1.70192972e-03, -1.85193986e-01, -1.30845919e-01,
          9.16091055e-02],
        [ 1.46897703e-01,  1.16454959e-01, -1.34158116e-02,
         -1.40886800e-02, -1.68336391e-01,  1.89078599e-01,
         -9.25426632e-02]], dtype=float32),
 array([-3.3968093 , -2.550803  ,  0.18469366,  0.17134538,  0.9993539 ,
        -3.9901173 ,  0.8954074 ], dtype=float32),
 array([[ 0.00101565],
        [-0.00312467],
        [-0.00216908],
        [-0.00427557],
        [-0.00295467],
        [ 0.00054993],
        [-0.00277636]], dtype=float32),
 array([-1.2525364], dtype=float32)]